logging:
  level:
    org:
      springframework:
        data:
          neo4j: DEBUG

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:neo4j:bolt://localhost:7687/
    username: neo4j
    password: 4312
  data:
    neo4j:
      username: neo4j
      password: 4312
      uri: bolt://localhost:7687
